# Generated by Django 2.2.3 on 2019-08-06 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address',
            new_name='postaladdress',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='dob',
            new_name='telephone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='zip',
        ),
    ]
