# Generated by Django 2.2 on 2019-07-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionaire',
            old_name='page',
            new_name='pages',
        ),
    ]
