# Generated by Django 2.2.3 on 2019-07-30 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_answers_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='category',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.Category'),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='category',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='questionaire', to='survey.Category'),
        ),
    ]
