# Generated by Django 2.2 on 2019-07-25 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20190725_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionaire',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questionaire', to='survey.Category'),
        ),
    ]
