# Generated by Django 2.2 on 2019-07-26 09:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20190725_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='questionId',
        ),
        migrations.AddField(
            model_name='answers',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.Category'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
